temp<-tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp,method = "curl")
house<-read.table(unz(temp,"household_power_consumption.txt"),sep=";",na.strings = "?",header = TRUE)
house$Date<-as.Date(house$Date,"%d/%m/%Y")
subhouse<-subset(house,Date==as.Date("01/02/2007",format="%d/%m/%Y")|Date==as.Date("02/02/2007",format="%d/%m/%Y"))
subhouse<-within(subhouse, { timestamp=format(as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S") })
par(mfrow = c(2,2))
plot(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Global_active_power"],type="l",ylab="Global Active Power",xlab="")
plot(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Voltage"],type="l",ylab="Voltage",xlab="datetime")
plot(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Sub_metering_1"],type="l",ylab="Energy sub metering",xlab="")
points(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Sub_metering_2"],type="l",col="red")
points(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Sub_metering_3"],type="l",col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),bty="n",cex=0.7,xjust = 1,y.intersp = 0.4)
plot(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Global_reactive_power"],type="l",ylab="Global_reactive_power",xlab="datetime")
dev.copy(png,"plot4.png")
dev.off()