temp<-tempfile()
par(mfrow = c(1,1))
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp,method = "curl")
house<-read.table(unz(temp,"household_power_consumption.txt"),sep=";",na.strings = "?",header = TRUE)
house$Date<-as.Date(house$Date,"%d/%m/%Y")
subhouse<-subset(house,Date==as.Date("01/02/2007",format="%d/%m/%Y")|Date==as.Date("02/02/2007",format="%d/%m/%Y"))
subhouse<-within(subhouse, { timestamp=format(as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S") })
plot(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Sub_metering_1"],type="l",ylab="Energy sub metering",xlab="")
points(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Sub_metering_2"],type="l",col="red")
points(strptime(subhouse[,"timestamp"],"%d/%m/%Y %H:%M:%S"),subhouse[,"Sub_metering_3"],type="l",col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1))
dev.copy(png,"plot3.png")
dev.off()

